# Generated by Django 5.0.4 on 2024-04-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Name', models.CharField(max_length=200)),
                ('Skill_Requirement', models.CharField(max_length=1000)),
                ('Budget_allocated', models.IntegerField()),
                ('Min_worker', models.IntegerField()),
                ('Max_worker', models.IntegerField()),
                ('Start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Name', models.CharField(max_length=200)),
                ('Skill_Requirement', models.CharField(max_length=1000)),
                ('Budget_allocated', models.IntegerField()),
                ('Min_worker', models.IntegerField()),
                ('Max_worker', models.IntegerField()),
                ('Start_date', models.DateField()),
            ],
        ),
    ]
