# Generated by Django 5.0.4 on 2024-04-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='Start_date',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='Budget_allocated',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='Max_worker',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='Min_worker',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='Skill_Requirement',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='Start_date',
        ),
    ]
