# Generated by Django 5.0.4 on 2024-04-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_employer_budget_allocated_employer_max_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='Start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
