# Generated by Django 5.0.4 on 2024-04-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_employer_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='Job_Name',
            new_name='Candi_name',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='Skill_Requirement',
            new_name='Skills',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Budget_allocated',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Max_worker',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Min_worker',
        ),
        migrations.AddField(
            model_name='candidate',
            name='End_date',
            field=models.DateField(default='2002-10-9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='Payment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='Start_date',
            field=models.DateField(default='2002-10-9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='mode',
            field=models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='offline', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='End_date',
            field=models.DateField(default='2002-10-9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='Job_type',
            field=models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='offline', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='Budget_allocated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Start_date',
            field=models.DateField(default='2002-10-9'),
            preserve_default=False,
        ),
    ]
